### ISSUE TITLE
请添加对百度云的 https 支持

### ISSUE THREAD

**Issue by violetcherry** [typcn/vp.baiduyun#1]
现在百度云推出了 https 加密连接，希望您的插件能支持 https 加密连接。

**Comment by typcn** [comment]
本地的 RPC 服务器是 http 的，给 localhost 签发一个证书大概是不可能的。。。。
总不能装根证书吧。。。Keyless SSL 目前还没有任何一种实现，重写一个需要不少时间。。

**Comment by violetcherry** [comment]
明白了，谢谢您的解答。
